#!/usr/bin/python
#Make sure to install to the apr package before you test the script 'sudo apt install net-tools -y'
#The below script is usefull to get the free ip's which are not connected in the given set.
import subprocess


for i in range(2,12):
    command=['ping', '-c', '1','-w','3', '192.168.1.'+str(i)]
    subprocess.call(command)

arpa = subprocess.check_output(("arp", "-a")).decode("ascii")
n_devices=len([x for x in arpa.split('\n') if '192.168.1.' in x and  
    all(y not in x for y in ['192.168.1.2','192.168.1.11']) ])
